### ISSUE TITLE
CentOS7:  error: failed to run custom build command for `pgx-pg-sys v0.5.0`

### ISSUE THREAD

**Issue by wonb168** [tcdi/pgx#761] opened 2022-10-14 08:44 UTC
when I `cargo pgx run pg10 `, raise 
**error:  failed to run custom build command for `pgx-pg-sys v0.5.0`
fatal error: 'stdbool.h' file not found**

```
cargo pgx run pg10 RUST_BACKTRACE=1
    Building extension with features pg10
     Running command "cargo" "build" "--features" "pg10" "--no-default-features" "--message-format=json-render-diagnostics"
   Compiling pgx-pg-sys v0.5.0
error: failed to run custom build command for `pgx-pg-sys v0.5.0`

Caused by:
  process didn't exit successfully: `/home/wcz/my_extension/target/debug/build/pgx-pg-sys-6ddcba8a0c67d23f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PGX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-changed=/home/wcz/.pgx/config.toml
  cargo:rerun-if-changed=include
  cargo:rerun-if-changed=cshim

  --- stderr
  manifest_dir=/home/wcz/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.5.0
  shim_src=/home/wcz/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.5.0/cshim
  shim_dst=/home/wcz/my_extension/target/debug/build/pgx-pg-sys-f6b1c4b18a1ca620/out/cshim
  Generating bindings for pg10
  warning: to: 'linker' input unused [-Wunused-command-line-argument]
  warning: missing: 'linker' input unused [-Wunused-command-line-argument]
  warning: header: 'linker' input unused [-Wunused-command-line-argument]
  warning: files: 'linker' input unused [-Wunused-command-line-argument]
  /home/wcz/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.5.0/include/pg10.h:9:10: fatal error: 'stdbool.h' file not found
  clang diag: warning: to: 'linker' input unused [-Wunused-command-line-argument]
  clang diag: warning: missing: 'linker' input unused [-Wunused-command-line-argument]
  clang diag: warning: header: 'linker' input unused [-Wunused-command-line-argument]
  clang diag: warning: files: 'linker' input unused [-Wunused-command-line-argument]
  thread 'main' panicked at 'Unable to generate bindings for pg10: ClangDiagnostic("/home/wcz/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.5.0/include/pg10.h:9:10: fatal error: 'stdbool.h' file not found\n")', /home/wcz/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.5.0/build.rs:563:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by workingjubilee** [comment] 2022-10-17 03:25
What is your operating system and which C compilers and/or C standard libraries are installed?

**Comment by wonb168** [comment] 2022-10-17 07:42
os: centos7
c: 3.4.5

**Comment by workingjubilee** [comment] 2022-10-17 17:16
CentOS 7 is only receiving purely maintenance updates, and we are about to discontinue support for Postgres 10. gcc 3.4.5 was released in 2005. We can't realistically support programming environments with C compilers that don't have full C99 support. This is because Postgres requires C99 now, and the Rust ecosystem also assumes C99 support as a baseline.

Even the Linux kernel is planning to move to C11 nowadays.

There's no new CentOS version per se: it's been discontinued in favor of CentOS Stream. You may want to consider migrating to CentOS Stream 9, Red Hat Enterprise Linux 9, Fedora Linux 36, AlmaLinux 9, or Rocky Linux 9.

**Comment by workingjubilee** [comment] 2022-10-18 00:29
Closing this since [getting a recent gcc on CentOS is documented in the README](https://github.com/tcdi/pgx/blob/master/README.md#system-requirements) and otherwise there's nothing we can realistically do: even if we wanted to support CentOS 7, Postgres will need a recent compiler, and so will bindgen.

**Closed by workingjubilee** 2022-10-18 00:29 UTC

**Comment by wonb168** [comment] 2022-10-18 09:05
clang -v #5.0.1
gcc -v #7.3.0
pgx : newest
when cargo pgx run pg13:

thread 'main' panicked at 'Unable to generate bindings for pg13: ClangDiagnostic("/usr/include/stdarg.h:32:10: fatal error: 'tr1/cstdarg' file not found\n")', /home/wcz/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.5.0/build.rs:563:13

**Comment by epgts** [comment] 2022-10-19 22:41
@wonb168 building on ancient centos 7 is challenging enough, can you avoid the additional challenge of ancient postgresql? :)

postgresql 10 end of life is just a few weeks away.

I can confirm that pgx builds and works on centos 7 + postgresql 14 at commit d62f517698ec97abf571a3aed84156dfba7aebc4 (which hopefully makes it into the next 0.5 patch).
