### ISSUE TITLE
SpiClient::select() seems to hang forever when you have a PgLwLock shared lock active

### ISSUE THREAD

**Issue by osawyerr** [tcdi/pgx#960] opened 2022-12-14 20:11 UTC
Hi,

I think I may have found a bug with the  way PgLwLock in a static variable initialised in _PG_init(), interacts with Spi. I don't believe its desired behaviour.

When you have a shared lock still in scope by calling ``PgLwLock::share()``  if you call ``Spi::connect() ---> SpiClient::select()``, the ``select()`` method hangs forever. However, dropping the lock before you call ``Spi::connect() ---> SpiClient::select()``, this behaviour is not observed and everything works ok. 

The ``PgLwLock`` is guarding a ``heapless::FnvIndexMap`` and a reference to one of its items is also active. But I don't believe that matters.

Some pseudo code to reproduce
```
let lock = SHARED_LOCK.share(); // SHARED_LOCK is a static PgLwLock initialised in _PG_init() in the normal way.

let query = "select col1 from foo_table where id = $1";
let args = vec![(PgBuiltInOids::TEXTOID.oid(), var_name.into_datum())];
    let retval = Spi::connect(|client| {
        let mut retval = vec![];
        let mut tup_table: SpiTupleTable =
                      client.select(query, None, Some(args)); // this line hangs forever
        while let Some(row) = tup_table.next() {
            ...
        }
        Ok(Some(retval))
    });
```

OS: MacOS
Postgres: pg14 and pg15
Pgx: 0.6.1

**Comment by EdMcBane** [comment] 2022-12-30 16:01
I've investigated this a bit, and seems actually worse than this.
First of all, it is not exclusive of `Spi`, but is triggered any time a `pg_guard`ed postgres function reports an error via `elog` while holding a lock.

```rust
static SHARED_LOCK: PgLwLock<i32> = PgLwLock::new();

#[pg_guard]
pub extern "C" fn _PG_init() {
    pg_shmem_init!(SHARED_LOCK);
}

#[pg_extern]
fn trigger_assertion_error() {
    // Hold lock
    let _lock = SHARED_LOCK.share();
    // Call into `pg_guard_ffi_boundary`-protected postgres function which internally reports an error
    unsafe { pg_sys::format_type_extended(pg_sys::InvalidOid, -1, 0) };
}
```

I've published a reproducer here: https://github.com/EdMcBane/pgx-bug960

The cause seems to be that `elog.c:errfinish()`, if the level is `ERROR`, resets `InterruptHoldoffCount` to zero.
`LwLockRelease` on the other hand assumes to be running in an interrupt holdoff section, and if run after `errfinish` will fail a `InterruptHoldoffCount > 0` assertion in the `RESUME_INTERRUPTS` macro.

So, while holding a lock:
* If we `error!` in rust code
  * the error is converted in a panic
  * the rust stack is unwound
  * the lock released
  * only once we hit the `pgx_extern_c_guard` barrier the panic gets turned into a postgres  `elog` and `errfinish` is called, resetting `InterruptHoldoffCount` without consequences
* If instead we call a `pg_guard_ffi_boundary`-protected postgres function which internally reports an error:
  * `errfinish` is called, resetting `InterruptHoldoffCount` to zero
  * a c forced unwind is triggered, rolling back the stack to the `pg_guard_ffi_boundary` barrier
  * the error is converted in a rust panic
  * the rust stack is unwound
  * the lock is released, but now `InterruptHoldoffCount` is zero and the assertion fails
  * postgres crashes

I haven't been able to reproduce it on macos, **I'm assuming** that the problem is the same but manifests itself differently in that case.

I'm not sure what the proper solution here would be; `PgLwLockShareGuard::drop` would need to avoid calling LWLockRelease if unwinding  was triggered by `errfinish`, as postgres in `src/backend/storage/lmgr/README` says that
>LWLock manager will automatically release held LWLocks during elog() recovery

**Comment by eeeebbbbrrrr** [comment] 2023-02-16 16:28
Have we confirmed that this issue is fixed?  Based on git history it should have been resolved as of 0.7.0-beta.1.  I feel like it has and we just forgot to close this issue?

**Comment by EdMcBane** [comment] 2023-02-16 21:24
I wasn't able to reproduce the behaviour exactly, and did not get feedback from @osawyerr about whether #988 was the underlying cause.
It should be easy for them to test now that pgx 0.7.0 is out, which incorporates the fix.

**Comment by eeeebbbbrrrr** [comment] 2023-02-16 21:40
Alrighty, I'll close this out.

**Closed by eeeebbbbrrrr** 2023-02-16 21:40 UTC
Labels: bug, pgx::spi
