### ISSUE TITLE
Empty log DETAIL: line

### ISSUE THREAD

**Issue by ccleve** [tcdi/pgx#1062] opened 2023-03-04 00:16 UTC
This is a pretty minor one. Whenever I use `pgx::log!("something")`, the log contains my LOG: message, followed by a line with a DETAIL: message which is empty. There is nothing following the DETAIL:.

I can turn this off using `set log_error_verbosity = 'TERSE';`, though that might cause me to miss seeing something useful.

It would be best to suppress the DETAIL: line if there is no detail to report.

I'm using 0.7.2

**Comment by workingjubilee** [comment] 2023-03-09 17:39
What triggers these DETAIL messages, anyways?

**Comment by eeeebbbbrrrr** [comment] 2023-03-09 17:45
Probably a logic bug that came from the Backtrace PR we recently merged

**Comment by ccleve** [comment] 2023-03-09 17:45
They appear with pgx::log!("stuff') and pgx::notice!("stuff");

**Comment by ewencp** [comment] 2023-03-11 01:37
I can confirm it was due to https://github.com/tcdi/pgx/commit/ee8c0cb6d914c697842ca15f5949c77082d0c869. If you have postgres-like regression tests running against a pgx extension it's pretty easy to catch since in this case it affects the output.

In general, what's the compatibility story for pgx? 0.7.3 had an incompatible API change too via https://github.com/tcdi/pgx/pull/1066. I'm pinning to specific versions but normally patch versions I'd expect to aim for only bugfixes/obviously compatible changes in a pre-1.0 project (but obviously requires more overhead/process since then bugfixes need to be maintained in parallel). Is it just major features ready for release that are triggering minor version bumps?

**Closed** 2023-03-14 14:52 UTC
